apiVersion: apps/v1
kind: Deployment
metadata:
  name: events-service
  namespace: cinemaabyss
  labels:
    app: events-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: events-service
  template:
    metadata:
      labels:
        app: events-service
    spec:
      containers:
      - name: events-service
        image: architecture-cinemaabyss-events-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8082
        env:
        - name: PORT
          value: "8082"
        - name: KAFKA_BROKERS
          value: "kafka:9092"
apiVersion: v1
kind: Service
metadata:
  name: events-service
  namespace: cinemaabyss
  labels:
    app: events-service
spec:
  selector:
    app: events-service
  ports:
  - port: 8082
    targetPort: 8082
  type: ClusterIP
