{{- if .Values.monolith.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monolith
  namespace: {{ .Values.global.namespace }}
  labels:
    app: monolith
    app.kubernetes.io/name: {{ include "cinemaabyss.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.monolith.replicas }}
  selector:
    matchLabels:
      app: monolith
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: monolith
    spec:
      containers:
      - name: monolith
        image: {{ .Values.monolith.image.repository }}:{{ .Values.monolith.image.tag }}
        imagePullPolicy: {{ .Values.monolith.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.monolith.service.targetPort }}
        # No environment variables for nginx container
        resources:
          {{- toYaml .Values.monolith.resources | nindent 10 }}
        # No health checks for nginx container
      restartPolicy: Always
      # No imagePullSecrets for nginx container
---
apiVersion: v1
kind: Service
metadata:
  name: monolith
  namespace: {{ .Values.global.namespace }}
  labels:
    app: monolith
    app.kubernetes.io/name: {{ include "cinemaabyss.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    app: monolith
  ports:
  - port: {{ .Values.monolith.service.port }}
    targetPort: {{ .Values.monolith.service.targetPort }}
  type: {{ .Values.monolith.service.type }}
{{- end }}