name: API Tests

on:
  push:
    branches: [ main, master, dev ]
  pull_request:
    branches: [ main, master, dev ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        required: true
        default: 'docker'
        type: choice
        options:
          - local
          - docker
      test_folder:
        description: 'Test folder to run (leave empty for all)'
        required: false
        type: string

jobs:
  api-tests:
    name: Run API Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: |
          # Docker Compose V2 is included in ubuntu-latest
          docker compose version
      
      - name: Start services with Docker Compose
        run: |
          echo "Starting Docker Compose services..."
          docker compose up -d
          echo "Services started, waiting for them to be ready..."
          sleep 180
          echo "Checking service status..."
          docker compose ps
      
      - name: Run API tests using Docker
        run: |
          echo "Running API tests using Docker test-runner..."
          # Use the test-runner service that's already configured in docker-compose.yml
          docker compose up test-runner --exit-code-from test-runner
          echo "Tests completed"
        
      
      - name: Stop services
        if: always()
        run: docker compose down
