name: API Tests

on:
  push:
    branches: [ main, master, dev ]
  pull_request:
    branches: [ main, master, dev ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        required: true
        default: 'docker'
        type: choice
        options:
          - local
          - docker
      test_folder:
        description: 'Test folder to run (leave empty for all)'
        required: false
        type: string

jobs:
  api-tests:
    name: Run API Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: |
          # Docker Compose V2 is included in ubuntu-latest
          docker compose version
      
      - name: Start services with Docker Compose
        run: |
          echo "Starting Docker Compose services..."
          docker compose up -d
          echo "Services started, waiting for them to be ready..."
          sleep 180
          echo "Checking service status..."
          docker compose ps
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: tests/postman/package-lock.json
      
      - name: Install Newman and dependencies
        working-directory: tests/postman
        run: npm install
      
      - name: Run API tests
        working-directory: tests/postman
        run: |
          # Run tests directly with Newman using docker environment
          npm run test:docker
        
      
      - name: Stop services
        if: always()
        run: docker compose down