name: Helm Deployment Test

on:
  workflow_dispatch:
  push:
    branches: [ main, dev ]
    paths:
      - 'src/kubernetes/**'
      - '.github/workflows/helm-test.yml'
  pull_request:
    branches: [ main, dev ]
    paths:
      - 'src/kubernetes/**'

jobs:
  helm-test:
    name: Test Helm Deployment
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Minikube
        uses: medyagh/setup-minikube@master
        with:
          driver: docker
          kubernetes-version: 'v1.25.0'

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.12.0'

      - name: Start Minikube
        run: |
          minikube start --driver=docker
          minikube status
          
      - name: Wait for Docker images
        run: |
          echo "Waiting for Docker images to be available..."
          # Check if required images are available
          docker pull ghcr.io/db-exp/cinemaabysstest/monolith:latest || echo "Monolith image not ready"
          docker pull ghcr.io/db-exp/cinemaabysstest/movies-service:latest || echo "Movies service image not ready"
          docker pull ghcr.io/db-exp/cinemaabysstest/events-service:latest || echo "Events service image not ready"
          docker pull ghcr.io/db-exp/cinemaabysstest/proxy-service:latest || echo "Proxy service image not ready"

      - name: Test Helm Chart
        run: |
          echo "Testing Helm chart syntax..."
          helm lint ./src/kubernetes/helm
          
          echo "Testing Helm template rendering..."
          helm template cinemaabyss ./src/kubernetes/helm --dry-run
          
          echo "Testing Helm installation..."
          helm install cinemaabyss ./src/kubernetes/helm --dry-run

      - name: Deploy to Minikube
        run: |
          echo "Creating namespace if not exists..."
          kubectl create namespace cinemaabyss --dry-run=client -o yaml | kubectl apply -f -
          
          echo "Deploying Helm chart to Minikube..."
          helm install cinemaabyss ./src/kubernetes/helm
          
          echo "Waiting for pods to be ready..."
          # Wait for pods in the cinemaabyss namespace
          kubectl wait --for=condition=ready pod -l app.kubernetes.io/instance=cinemaabyss -n cinemaabyss --timeout=300s || echo "Some pods may still be starting"
          
          echo "Checking pod status..."
          kubectl get pods -n cinemaabyss
          
          echo "Checking services..."
          kubectl get services -n cinemaabyss
          
          
      - name: Test Service Connectivity
        run: |
          echo "Testing service connectivity..."
          # Wait for services to be ready
          sleep 30
          
          # Check if all pods are running
          echo "Checking pod status after waiting..."
          kubectl get pods -n cinemaabyss -o wide
          
          # Count running pods
          RUNNING_PODS=$(kubectl get pods -n cinemaabyss --no-headers | grep -c "Running")
          TOTAL_PODS=$(kubectl get pods -n cinemaabyss --no-headers | wc -l)
          
          echo "Running pods: $RUNNING_PODS out of $TOTAL_PODS"
          
          if [ "$RUNNING_PODS" -gt 0 ]; then
            echo "✅ Helm deployment test completed successfully!"
          else
            echo "❌ No pods are running, deployment may have failed"
            exit 1
          fi

      - name: Cleanup
        if: always()
        run: |
          echo "Cleaning up Helm deployment..."
          helm uninstall cinemaabyss || true
          minikube stop || true
